/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import AccesoADatos.GlobalException;
import AccesoADatos.NoDataException;
import Control.ControlProfesor;
import LogicaDeNegocio.Profesor;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yenny
 */
public class MantenimientoProfesor extends javax.swing.JFrame {
    Profesor profesor;
    ControlProfesor control;
    DefaultTableModel tablaProfesor= new DefaultTableModel(); 
    int seleccion;
    String idBuscar = "";
    
    public MantenimientoProfesor() throws GlobalException, NoDataException {
        this.profesor = Profesor.getINSTANCE();
        this.control = ControlProfesor.getINSTANCE();
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_agregarProfesor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_profesor = new javax.swing.JTable();
        txt_buscar_profesor = new javax.swing.JTextField();
        lbl_buscar = new javax.swing.JLabel();
        btn_volver = new javax.swing.JButton();
        lbl_mantenimientoProfesores = new javax.swing.JLabel();
        btn_borrarProfesor = new javax.swing.JButton();
        btn_listarProfesor = new javax.swing.JButton();
        btn_modificarProfesor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        btn_agregarProfesor.setBackground(new java.awt.Color(204, 204, 204));
        btn_agregarProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.png"))); // NOI18N
        btn_agregarProfesor.setToolTipText("");
        btn_agregarProfesor.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 204, 0)));
        btn_agregarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarProfesorActionPerformed(evt);
            }
        });

        tbl_profesor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbl_profesor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_profesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_profesorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_profesor);

        txt_buscar_profesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscar_profesorActionPerformed(evt);
            }
        });

        lbl_buscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_buscar.setText("Buscar Profesor:");

        btn_volver.setBackground(new java.awt.Color(204, 204, 204));
        btn_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver.png"))); // NOI18N
        btn_volver.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 204)));
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });

        lbl_mantenimientoProfesores.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_mantenimientoProfesores.setText("Mantenimiento de Profesores");

        btn_borrarProfesor.setBackground(new java.awt.Color(204, 204, 204));
        btn_borrarProfesor.setForeground(new java.awt.Color(255, 0, 0));
        btn_borrarProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar.png"))); // NOI18N
        btn_borrarProfesor.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        btn_borrarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarProfesorActionPerformed(evt);
            }
        });

        btn_listarProfesor.setBackground(new java.awt.Color(204, 204, 204));
        btn_listarProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actualizar.png"))); // NOI18N
        btn_listarProfesor.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 204)));
        btn_listarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listarProfesorActionPerformed(evt);
            }
        });

        btn_modificarProfesor.setBackground(new java.awt.Color(204, 204, 204));
        btn_modificarProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Editar.png"))); // NOI18N
        btn_modificarProfesor.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
        btn_modificarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarProfesorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(72, 72, 72)
                            .addComponent(lbl_mantenimientoProfesores))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbl_buscar)
                            .addGap(18, 18, 18)
                            .addComponent(txt_buscar_profesor, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_agregarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_modificarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_listarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_borrarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_mantenimientoProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_borrarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_listarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_agregarProfesor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_buscar_profesor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_buscar))
                    .addComponent(btn_modificarProfesor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarProfesorActionPerformed
        FormularioProfesor formulario = new FormularioProfesor();
        formulario.setVisible(true);
        this.dispose();
        formulario.identificadorDeAccion(2,profesor);
    }//GEN-LAST:event_btn_agregarProfesorActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        new MenuMatricula().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_volverActionPerformed

    public void llenarTabla() throws GlobalException, NoDataException{
        tablaProfesor.addColumn("Cédula");
        tablaProfesor.addColumn("Nombre");
        tablaProfesor.addColumn("Teléfono");
        tablaProfesor.addColumn("Email");
        tablaProfesor.addColumn("Usuario");
      
        this.tbl_profesor.setModel(tablaProfesor);


        ArrayList<Profesor>lista = control.listarProfesores();
        Object[] fila = new Object[tablaProfesor.getColumnCount()];
        for (int i = 0; i < lista.size(); i++) {
           fila[0] = lista.get(i).getId_profesor();
           fila[1] = lista.get(i).getNombre_profesor();
           fila[2] = lista.get(i).getTelefono_profesor();
           fila[3] = lista.get(i).getEmail_profesor();
           fila[4] = lista.get(i).getUsuario_num_ced();
           tablaProfesor.addRow(fila);
        }
    }
    
    public void limpiarTabla(){
        tablaProfesor.setRowCount(0);
    }
    
    private void txt_buscar_profesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscar_profesorActionPerformed
        try {
            // TODO add your handling code here:
            limpiarTabla();
            idBuscar = txt_buscar_profesor.getText();
            ArrayList<Profesor>lista = control.buscarProfesor(idBuscar);
            Object[] fila = new Object[tablaProfesor.getColumnCount()];
            for (int i = 0; i < lista.size(); i++) {
                fila[0] = lista.get(i).getId_profesor();
                fila[1] = lista.get(i).getNombre_profesor();
                fila[2] = lista.get(i).getTelefono_profesor();
                fila[3] = lista.get(i).getEmail_profesor();
                fila[4] = lista.get(i).getUsuario_num_ced();
                tablaProfesor.addRow(fila);
            }
        } catch (GlobalException ex) {
            JOptionPane.showMessageDialog(null, "No se encontró el profesor","",JOptionPane.ERROR_MESSAGE);
            btn_listarProfesorActionPerformed(evt);
            Logger.getLogger(MantenimientoAlumno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoDataException ex) {
            JOptionPane.showMessageDialog(null, "No se encontró el profesor","",JOptionPane.ERROR_MESSAGE);
            btn_listarProfesorActionPerformed(evt);
            Logger.getLogger(MantenimientoAlumno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txt_buscar_profesorActionPerformed

    private void btn_borrarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarProfesorActionPerformed
        int filaSelec = tbl_profesor.getSelectedRow();
        if(filaSelec >= 0){
            if(control.eliminarProfesor((String) tbl_profesor.getValueAt(seleccion,0)) == false){
                JOptionPane.showMessageDialog(null, "Profesor eliminado correctamente");
            }else{
                JOptionPane.showMessageDialog(null, "Error al eliminar profesor","",JOptionPane.ERROR_MESSAGE);
            }
            
            //actualizar tabla
            try {
                limpiarTabla();
                tablaProfesor.setColumnCount(0);
                llenarTabla();
            } catch (GlobalException ex) {
                Logger.getLogger(MantenimientoProfesor.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NoDataException ex) {                
                Logger.getLogger(MantenimientoProfesor.class.getName()).log(Level.SEVERE, null, ex);
            }        }else{
            JOptionPane.showMessageDialog(this, "Seleccione una fila a eliminar","",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_borrarProfesorActionPerformed

    private void tbl_profesorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_profesorMouseClicked
        seleccion = tbl_profesor.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_tbl_profesorMouseClicked

    private void btn_listarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listarProfesorActionPerformed
        try {
            limpiarTabla();
            tablaProfesor.setColumnCount(0);
            llenarTabla();
        } catch (GlobalException ex) {
            Logger.getLogger(MantenimientoAlumno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoDataException ex) {
            Logger.getLogger(MantenimientoAlumno.class.getName()).log(Level.SEVERE, null, ex);
        }
        txt_buscar_profesor.setText("");
    }//GEN-LAST:event_btn_listarProfesorActionPerformed

    private void btn_modificarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarProfesorActionPerformed
        int filaSelec = tbl_profesor.getSelectedRow();
        if(filaSelec >= 0){
            profesor.setId_profesor((String) tbl_profesor.getValueAt(seleccion, 0));
            profesor.setNombre_profesor((String) tbl_profesor.getValueAt(seleccion, 1));
            profesor.setTelefono_profesor((String) tbl_profesor.getValueAt(seleccion, 2));
            profesor.setEmail_profesor((String) tbl_profesor.getValueAt(seleccion, 3));
            profesor.setUsuario_num_ced((String) tbl_profesor.getValueAt(seleccion, 4));
            
            FormularioProfesor formulario = new FormularioProfesor();
            formulario.setVisible(true);
            this.dispose();
            formulario.identificadorDeAccion(1,profesor);
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione una fila a editar");
        }
    }//GEN-LAST:event_btn_modificarProfesorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregarProfesor;
    private javax.swing.JButton btn_borrarProfesor;
    private javax.swing.JButton btn_listarProfesor;
    private javax.swing.JButton btn_modificarProfesor;
    private javax.swing.JButton btn_volver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_buscar;
    private javax.swing.JLabel lbl_mantenimientoProfesores;
    private javax.swing.JTable tbl_profesor;
    private javax.swing.JTextField txt_buscar_profesor;
    // End of variables declaration//GEN-END:variables
}
