/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Control.ControlAlumno;
import LogicaDeNegocio.Alumno;

/**
 *
 * @author josue
 */
public class FormularioAlumno extends javax.swing.JFrame {

    ControlAlumno control = new ControlAlumno();
    Alumno alumno = new Alumno();
    
    public FormularioAlumno() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_cedula = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_telefono = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        txt_cedula_alumno = new javax.swing.JTextField();
        txt_nombre_alumno = new javax.swing.JTextField();
        txt_telefono_alumno = new javax.swing.JTextField();
        txt_email_alumno = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_limpiar = new javax.swing.JButton();
        lbl_nacimiento = new javax.swing.JLabel();
        txt_nacimiento_alumno = new javax.swing.JTextField();
        btn_volver = new javax.swing.JButton();
        lbl_codigoCarrera = new javax.swing.JLabel();
        txt_codigoCarrera_alumno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_cedula.setText("Cédula:");

        lbl_nombre.setText("Nombre:");

        lbl_telefono.setText("Teléfono:");

        lbl_email.setText("Email:");

        txt_cedula_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cedula_alumnoActionPerformed(evt);
            }
        });

        txt_telefono_alumno.setToolTipText("");
        txt_telefono_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefono_alumnoActionPerformed(evt);
            }
        });

        txt_email_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_email_alumnoActionPerformed(evt);
            }
        });

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Agregar Alumno");

        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        lbl_nacimiento.setText("Fecha de Nacimiento:");

        txt_nacimiento_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nacimiento_alumnoActionPerformed(evt);
            }
        });

        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });

        lbl_codigoCarrera.setText("Codigo de carrera:");

        txt_codigoCarrera_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigoCarrera_alumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_volver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(105, 105, 105))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_telefono)
                                .addComponent(lbl_email, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_nombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_cedula, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lbl_nacimiento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_codigoCarrera)
                        .addGap(23, 23, 23)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_limpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_guardar))
                    .addComponent(txt_email_alumno, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(txt_nombre_alumno)
                    .addComponent(txt_telefono_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cedula_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txt_nacimiento_alumno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(txt_codigoCarrera_alumno, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btn_volver))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cedula_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cedula))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombre)
                    .addComponent(txt_nombre_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_telefono)
                    .addComponent(txt_telefono_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_email)
                    .addComponent(txt_email_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_codigoCarrera)
                    .addComponent(txt_codigoCarrera_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nacimiento)
                    .addComponent(txt_nacimiento_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar)
                    .addComponent(btn_limpiar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cedula_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cedula_alumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cedula_alumnoActionPerformed

    private void txt_telefono_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefono_alumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefono_alumnoActionPerformed

    private void txt_email_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_email_alumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_email_alumnoActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        new MantenimientoAlumno().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_volverActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        alumno.setId_alumno(txt_cedula_alumno.getText());
        alumno.setNombre_alumno(txt_nombre_alumno.getText());
        alumno.setTelefono_alumno(txt_telefono_alumno.getText());
        alumno.setEmail_alumno(txt_email_alumno.getText());
        alumno.setCarreras_cod_carr(txt_codigoCarrera_alumno.getText());
        alumno.setFechaNacimiento(txt_nacimiento_alumno.getText());
        alumno.setUsuarios_num_ced(txt_cedula_alumno.getText());
        
        control.ingresarAlumno(alumno);
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        txt_cedula_alumno.setText("");
        txt_nombre_alumno.setText("");
        txt_telefono_alumno.setText("");
        txt_email_alumno.setText("");
        txt_codigoCarrera_alumno.setText("");
        txt_nacimiento_alumno.setText("");
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void txt_nacimiento_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nacimiento_alumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nacimiento_alumnoActionPerformed

    private void txt_codigoCarrera_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigoCarrera_alumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoCarrera_alumnoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_cedula;
    private javax.swing.JLabel lbl_codigoCarrera;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_nacimiento;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_telefono;
    private javax.swing.JTextField txt_cedula_alumno;
    private javax.swing.JTextField txt_codigoCarrera_alumno;
    private javax.swing.JTextField txt_email_alumno;
    private javax.swing.JTextField txt_nacimiento_alumno;
    private javax.swing.JTextField txt_nombre_alumno;
    private javax.swing.JTextField txt_telefono_alumno;
    // End of variables declaration//GEN-END:variables
}
