/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import AccesoADatos.GlobalException;
import AccesoADatos.NoDataException;
import Control.ControlCurso;
import LogicaDeNegocio.Curso;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yenny
 */
public class MantenimientoCurso extends javax.swing.JFrame {

    ControlCurso control = new ControlCurso();
    DefaultTableModel tablaCurso= new DefaultTableModel(); 
    
    public MantenimientoCurso() throws GlobalException, NoDataException {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null); 
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_agregar_curso = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_curso = new javax.swing.JTable();
        txt_buscar_curso = new javax.swing.JTextField();
        lbl_buscar = new javax.swing.JLabel();
        btn_volver = new javax.swing.JButton();
        lbl_mantenimientoCursos = new javax.swing.JLabel();
        btn_borrarCurso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_agregar_curso.setText("Agregar");
        btn_agregar_curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_cursoActionPerformed(evt);
            }
        });

        tbl_curso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_curso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_cursoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_curso);

        lbl_buscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_buscar.setText("Buscar Curso:");

        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });

        lbl_mantenimientoCursos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_mantenimientoCursos.setText("Mantenimiento de Cursos");

        btn_borrarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar.png"))); // NOI18N
        btn_borrarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_buscar)
                                .addGap(18, 18, 18)
                                .addComponent(txt_buscar_curso, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_agregar_curso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_borrarCurso))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_volver)
                        .addGap(81, 81, 81)
                        .addComponent(lbl_mantenimientoCursos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_mantenimientoCursos)
                    .addComponent(btn_volver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_buscar_curso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_buscar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btn_agregar_curso))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_borrarCurso)))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregar_cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_cursoActionPerformed
        new FormularioCurso().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_agregar_cursoActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        new MenuMatricula().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_volverActionPerformed

    public void llenarTabla() throws GlobalException, NoDataException{
        tablaCurso.addColumn("Código");
        tablaCurso.addColumn("Nombre");
        tablaCurso.addColumn("Creditos");
        tablaCurso.addColumn("Horas Semanales");
      
        this.tbl_curso.setModel(tablaCurso);


        ArrayList<Curso>lista = control.listarCurso();
        Object[] fila = new Object[tablaCurso.getColumnCount()];
        for (int i = 0; i < lista.size(); i++) {
           fila[0] = lista.get(i).getCodigo_curso();
           fila[1] = lista.get(i).getNombre_curso();
           fila[2] = lista.get(i).getCreditos();
           fila[3] = lista.get(i).getHoras_semanales();
           tablaCurso.addRow(fila);
        }
    }
    
    public void limpiarTabla(){
        tablaCurso.setRowCount(0);
    }
    
    private void btn_borrarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarCursoActionPerformed

    }//GEN-LAST:event_btn_borrarCursoActionPerformed

    private void tbl_cursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_cursoMouseClicked
        int seleccion = tbl_curso.rowAtPoint(evt.getPoint());
        control.eliminarCurso((String) tbl_curso.getValueAt(seleccion,0));
    }//GEN-LAST:event_tbl_cursoMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar_curso;
    private javax.swing.JButton btn_borrarCurso;
    private javax.swing.JButton btn_volver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_buscar;
    private javax.swing.JLabel lbl_mantenimientoCursos;
    private javax.swing.JTable tbl_curso;
    private javax.swing.JTextField txt_buscar_curso;
    // End of variables declaration//GEN-END:variables
}
